default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost
  port: 5432
development:
  <<: *default
  database: <%= ENV['HARLEN_DDB_DB'] %>
  username: <%= ENV['HARLEN_DDB_USER'] %>
  password: <%= ENV['HARLEN_DDB_PASS'] %>
test:
  <<: *default
  database: <%= ENV['HARLEN_TDB_DB'] %>
  username: <%= ENV['HARLEN_TDB_USER'] %>
  password: <%= ENV['HARLEN_TDB_PASS'] %>
production:
  <<: *default
  database: <%= ENV['HARLEN_PDB_DB'] %>
  username: <%= ENV['HARLEN_PDB_USER'] %>
  password: <%= ENV['HARLEN_PDB_PASS'] %>
